d_Capitais_API_IBGE

let
    Fonte = Json.Document(Web.Contents("https://servicodados.ibge.gov.br/api/v3/agregados/1287/periodos/2010/variaveis/591?localidades=N6")),
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"id", "variavel", "unidade", "resultados"}, {"id", "variavel", "unidade", "resultados"}),
    #"Valor Substituído" = Table.ReplaceValue(#"Column1 Expandido","População nos municípios das capitais","Populacao_Capitais",Replacer.ReplaceText,{"variavel"}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Valor Substituído",{"id", "unidade"}),
    #"resultados Expandido" = Table.ExpandListColumn(#"Colunas Removidas", "resultados"),
    #"resultados Expandido1" = Table.ExpandRecordColumn(#"resultados Expandido", "resultados", {"series"}, {"resultados.series"}),
    #"resultados.series Expandido" = Table.ExpandListColumn(#"resultados Expandido1", "resultados.series"),
    #"resultados.series Expandido1" = Table.ExpandRecordColumn(#"resultados.series Expandido", "resultados.series", {"localidade", "serie"}, {"localidade", "serie"}),
    #"localidade Expandido" = Table.ExpandRecordColumn(#"resultados.series Expandido1", "localidade", {"id", "nome"}, {"id_Muni", "Municipio"}),
    #"serie Expandido" = Table.ExpandRecordColumn(#"localidade Expandido", "serie", {"2010"}, {"2010"}),
    #"Coluna em pivô" = Table.Pivot(#"serie Expandido", List.Distinct(#"serie Expandido"[variavel]), "variavel", "2010"),
    #"Primeiros Caracteres Inseridos" = Table.AddColumn(#"Coluna em pivô", "idUF", each Text.Start([id_Muni], 2), type text),
    #"Colunas Removidas1" = Table.RemoveColumns(#"Primeiros Caracteres Inseridos",{"Populacao_Capitais"}),
    #"Cria Col MunicipioMaiusculo" = Table.AddColumn(#"Colunas Removidas1", "MunicipioMaiusculo", each Text.BeforeDelimiter([Municipio], " - "), type text),
    #"Texto em Maiúscula" = Table.TransformColumns(#"Cria Col MunicipioMaiusculo",{{"MunicipioMaiusculo", Text.Upper, type text}}),
    Personalizar1 = Table.TransformColumns(#"Texto em Maiúscula",{{"MunicipioMaiusculo", F_Tira_Ascento, type text}}),
    #"Cria Col Caminho" = Table.AddColumn(Personalizar1, "Caminho", each Caminho),
    #"Executar script Python" = Python.Execute("# 'dataset' tem os dados de entrada para este script#(lf)# -*- encoding: utf-8 -*-#(lf)import pandas as pd#(lf)import os#(lf)from datetime import date#(lf)#(lf)# Pega o Caminho já definido#(lf)caminho = dataset['Caminho'][0]#(lf)#(lf)# Seleciona o caminho do Arquivo#(lf)basedir = caminho + ""/ArquivosParaUnificar/""#(lf)#(lf)# Nome do arquivo#(lf)nomearq = ""d_Capitais_API_IBGE.csv""#(lf)#(lf)# cria um diretório para armazenar o arquivo comparâmetro para não criar se já existir#(lf)os.makedirs(os.path.abspath(os.path.dirname(basedir)), exist_ok=True)#(lf)#(lf)basedir = os.path.abspath(os.path.dirname(basedir))#(lf)#(lf)# Apaga o arquivo se foi criado#(lf)if os.path.isfile(os.path.join(basedir, nomearq)):#(lf)  # Se existe apaga o arquivo#(lf)  os.remove(os.path.join(basedir, nomearq))#(lf)#(lf)# Salva o arquivo na Pasta de unificação#(lf)dataset[[""id_Muni"", ""Municipio"", ""idUF"", ""MunicipioMaiusculo""]].to_csv(os.path.join(basedir, nomearq), index = False, sep =';')#(lf)#(lf)dataset = dataset[[""id_Muni"", ""Municipio"", ""idUF"", ""MunicipioMaiusculo""]]#(lf)print(dataset)",[dataset=#"Cria Col Caminho"]),
    dataset = #"Executar script Python"{[Name="dataset"]}[Value],
    #"Tipo Alterado" = Table.TransformColumnTypes(dataset,{{"id_Muni", Int64.Type}, {"Municipio", type text}, {"idUF", Int64.Type}})
in
    #"Tipo Alterado"