d_Municipios_API_IBGE

let
    Fonte = Json.Document(Web.Contents("https://servicodados.ibge.gov.br/api/v1/localidades/estados/11|12|13|14|15|16|17|21|22|23|24|25|26|27|28|29|31|32|33|35|41|42|43|50|51|52|53/municipios")),
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Col Região Expandida" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"id", "nome", "regiao-imediata"}, {"id", "nome", "regiao-imediata"}),
    #"regiao-imediata Expandido" = Table.ExpandRecordColumn(#"Col Região Expandida", "regiao-imediata", {"regiao-intermediaria"}, {"regiao-intermediaria"}),
    #"regiao-intermediaria Expandido" = Table.ExpandRecordColumn(#"regiao-imediata Expandido", "regiao-intermediaria", {"UF"}, {"UF"}),
    #"UF Expandido" = Table.ExpandRecordColumn(#"regiao-intermediaria Expandido", "UF", {"id", "sigla", "nome"}, {"idUF", "sigla", "nomeUF"}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"UF Expandido",{{"id", "idMun"}, {"nome", "Municipio"}}),
    #"Mescla Col Municipio + UF" = Table.AddColumn(#"Colunas Renomeadas", "MunicipioUF", each Text.Combine({[Municipio], [sigla]}, " - "), type text),
    #"Tira Ascentos" = Table.AddColumn(#"Mescla Col Municipio + UF", "MunUFMaiuscula", each TiraAscento([MunicipioUF])),
    #"Texto em Maiúscula" = Table.TransformColumns(#"Tira Ascentos",{{"MunUFMaiuscula", Text.Upper, type text}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Texto em Maiúscula",{{"idMun", Int64.Type}, {"idUF", Int64.Type}, {"Municipio", type text}, {"sigla", type text}, {"nomeUF", type text}})
in
    #"Tipo Alterado"


METADADOS:
Disponibiliza  os Municípios das UFs com os códigos padronizados pelo IBGE.
