f_Arrec_UFs_CONFAZ

let
    Fonte = Excel.Workbook(Web.Contents("https://www.confaz.fazenda.gov.br/20221010_sigdef.xls"), null, true),
    arrecadacao1 = Fonte{[Name="arrecadacao"]}[Data],
    #"Tipo Alterado" = Table.TransformColumnTypes(arrecadacao1,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}}),
    #"Linhas Principais Removidas" = Table.Skip(#"Tipo Alterado",1),
    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Principais Removidas", [PromoteAllScalars=true]),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"id_uf", Int64.Type}, {"ESTADO", type text}, {"ANO23", type text}, {"ANO", type text}, {"MÊS2", type text}, {"1.1 - PRIMÁRIO", Int64.Type}, {"1.2 - SECUNDÁRIO", Int64.Type}, {"1.3 - TERCIÁRIO", Int64.Type}, {"1.3.1 - COMÉRCIO ATACADISTA", Int64.Type}, {"1.3.2 - COMÉRCIO VAREJISTA", Int64.Type}, {"1.3.3 - SERVIÇOS DE TRANSPORTE", Int64.Type}, {"1.3.4 - SERVIÇOS DE COMUNICAÇÃO", Int64.Type}, {"1.3.5 - OUTROS", Int64.Type}, {"2.1 - ENERGIA ELÉTRICA", Int64.Type}, {"2.1.1 - SETOR SECUNDÁRIO ", Int64.Type}, {"2.1.2 - SETOR TERCIÁRIO", Int64.Type}, {"2.2 - PETRÓLEO, COMBUSTÍVEIS E LUBRIFICANTES", Int64.Type}, {"2.2.1 - SETOR SECUNDÁRIO", Int64.Type}, {"2.2.2 - SETOR TERCIÁRIO", Int64.Type}, {"2.3 - DÍVIDA ATIVA", Int64.Type}, {"2.4 - OUTRAS FONTES DE RECEITAS", Int64.Type}, {"TOTAL DA ARRECADAÇÃO DO ICMS", Int64.Type}, {"IPVA", Int64.Type}, {"ITCD", Int64.Type}, {"TAXAS", Int64.Type}, {"OUTROS", Int64.Type}, {"TOTAL ARRECADAÇÃO DE OUTROS TRIBUTOS", Int64.Type}, {"TOTAL GERAL DA RECEITA TRIBUTÁRIA ", Int64.Type}, {"Coluna1", type text}, {"Coluna2", type text}, {"Coluna3", type text}, {"Coluna4", type logical}, {"Column33", type text}}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado1",{"Column33", "Coluna3", "Coluna2", "Coluna1", "id_uf"}),
    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([ESTADO] <> null)),
    #"Colunas Mescladas" = Table.CombineColumns(#"Linhas Filtradas",{"MÊS2", "ANO"},Combiner.CombineTextByDelimiter("/", QuoteStyle.None),"Data"),
    #"Prefixo ""15/"" Adicionado" = Table.TransformColumns(#"Colunas Mescladas", {{"Data", each "15/" & _, type text}}),
    #"Data Analisada" = Table.TransformColumns(#"Prefixo ""15/"" Adicionado",{{"Data", each Date.From(DateTimeZone.From(_)), type date}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Data Analisada",{{"TOTAL GERAL DA RECEITA TRIBUTÁRIA ", "TotRecTributaria"}, {"TOTAL ARRECADAÇÃO DE OUTROS TRIBUTOS", "TotOutrosTributos"}}),
    #"Texto Aparado" = Table.TransformColumns(#"Colunas Renomeadas",{{"ESTADO", Text.Trim, type text}}),
    #"Substitui Espírito Santo" = Table.ReplaceValue(#"Texto Aparado","Espírito Santos","Espírito Santo",Replacer.ReplaceText,{"ESTADO"}),
    #"Substitui Goiás" = Table.ReplaceValue(#"Substitui Espírito Santo","Goias","Goiás",Replacer.ReplaceText,{"ESTADO"}),
    #"Filtra Menor Data" = Table.SelectRows(#"Substitui Goiás", each [Data] > Date.AddYears(MenorData,-1)),
    #"Consultas Mescladas" = Table.NestedJoin(#"Filtra Menor Data", {"ESTADO"}, d_Estados_API_IBGE, {"nome"}, "d_Estados_API_IBGE", JoinKind.LeftOuter),
    #"d_Estados_API_IBGE Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "d_Estados_API_IBGE", {"idUF", "sigla", "nome"}, {"idUF", "sigla", "nome"}),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"d_Estados_API_IBGE Expandido",{"ANO23", "Data", "1.1 - PRIMÁRIO", "1.2 - SECUNDÁRIO", "1.3 - TERCIÁRIO", "1.3.1 - COMÉRCIO ATACADISTA", "1.3.2 - COMÉRCIO VAREJISTA", "1.3.3 - SERVIÇOS DE TRANSPORTE", "1.3.4 - SERVIÇOS DE COMUNICAÇÃO", "1.3.5 - OUTROS", "2.1 - ENERGIA ELÉTRICA", "2.1.1 - SETOR SECUNDÁRIO ", "2.1.2 - SETOR TERCIÁRIO", "2.2 - PETRÓLEO, COMBUSTÍVEIS E LUBRIFICANTES", "2.2.1 - SETOR SECUNDÁRIO", "2.2.2 - SETOR TERCIÁRIO", "2.3 - DÍVIDA ATIVA", "2.4 - OUTRAS FONTES DE RECEITAS", "TOTAL DA ARRECADAÇÃO DO ICMS", "IPVA", "ITCD", "TAXAS", "OUTROS", "TotOutrosTributos", "TotRecTributaria", "Coluna4", "ESTADO", "idUF", "sigla", "nome"}),
    // A Coluna "TOTAL DA ARRECADAÇÃO DO ICMS" foi removida por ser a soma das colunas: [1.3 - TERCIÁRIO], [1.2 - SECUNDÁRIO], [1.1 - PRIMÁRIO], [2.1 - ENERGIA ELÉTRICA], [2.2 - PETRÓLEO, COMBUSTÍVEIS E LUBRIFICANTES], [2.3 - DÍVIDA ATIVA], [2.4 - OUTRAS FONTES DE RECEITAS].
    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Reordenadas",{"nome", "ESTADO", "TOTAL DA ARRECADAÇÃO DO ICMS"}),
    #"Consultas Mescladas1" = Table.NestedJoin(#"Colunas Removidas1", {"idUF"}, d_Capitais_ESTUDO, {"idUF"}, "d_Capitais_ESTUDO", JoinKind.RightOuter),
    #"d_Capitais_ESTUDO Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "d_Capitais_ESTUDO", {"id_Muni"}, {"id_Muni"}),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"d_Capitais_ESTUDO Expandido",{{"1.3.1 - COMÉRCIO ATACADISTA", "ICMS_STC_ATACADISTA"}, {"1.3.2 - COMÉRCIO VAREJISTA", "ICMS_STC_VAREJISTA"}, {"1.3.3 - SERVIÇOS DE TRANSPORTE", "ICMS_STS_TRANSPORTE"}, {"1.3.4 - SERVIÇOS DE COMUNICAÇÃO", "ICMS_STS_COMUNICACAO"}, {"1.3.5 - OUTROS", "ICMS_ST_OUTROS"}}),
    // A Coluna "1.3 - TERCIÁRIO" foi removida por ser a soma das colunas: "1.3.1 - COMÉRCIO ATACADISTA", "ICMS_STC_ATACADISTA"}, {"1.3.2 - COMÉRCIO VAREJISTA", "ICMS_STC_VAREJISTA"}, {"1.3.3 - SERVIÇOS DE TRANSPORTE", "ICMS_STS_TRANSPORTE"}, {"1.3.4 - SERVIÇOS DE COMUNICAÇÃO", "ICMS_STS_COMUNICACAO"}, {"1.3.5 - OUTROS", "ICMS_ST_OUTROS" 
    #"Remove Col ""1.3 - TERCIÁRIO"" " = Table.RemoveColumns(#"Colunas Renomeadas1",{"1.3 - TERCIÁRIO"}),
    #"Colunas Renomeadas2" = Table.RenameColumns(#"Remove Col ""1.3 - TERCIÁRIO"" ",{{"1.1 - PRIMÁRIO", "ICMS_Setor_PRIMARIO"}, {"1.2 - SECUNDÁRIO", "ICMS_Setor_SECUNDARIO"}}),
    #"Remove Col ""2.1 - ENERGIA ELÉTRICA""" = Table.RemoveColumns(#"Colunas Renomeadas2",{ "2.1.1 - SETOR SECUNDÁRIO ", "2.1.2 - SETOR TERCIÁRIO"}),
    #"Colunas Renomeadas4" = Table.RenameColumns(#"Remove Col ""2.1 - ENERGIA ELÉTRICA""",{{"2.2 - PETRÓLEO, COMBUSTÍVEIS E LUBRIFICANTES", "ICMS_PetroCombusLubr"}, {"2.1 - ENERGIA ELÉTRICA", "ICMS_ENERGIA"}}),
    #"Colunas Removidas2" = Table.RemoveColumns(#"Colunas Renomeadas4",{"2.2.1 - SETOR SECUNDÁRIO", "2.2.2 - SETOR TERCIÁRIO", "ANO23"}),
    #"Colunas Renomeadas5" = Table.RenameColumns(#"Colunas Removidas2",{{"2.3 - DÍVIDA ATIVA", "ICMS_DivAtiva"}, {"2.4 - OUTRAS FONTES DE RECEITAS", "ICMS_OUTRAS"}}),
    #"Linhas Filtradas1" = Table.SelectRows(#"Colunas Renomeadas5", each true),
    #"Linhas Classificadas" = Table.Sort(#"Linhas Filtradas1",{{"Data", Order.Descending}}),
    #"Substitui null /ZERO" = Table.ReplaceValue(#"Linhas Classificadas",null,0,Replacer.ReplaceValue,{"ICMS_Setor_PRIMARIO", "ICMS_Setor_SECUNDARIO", "ICMS_STC_ATACADISTA", "ICMS_STC_VAREJISTA", "ICMS_STS_TRANSPORTE", "ICMS_STS_COMUNICACAO", "ICMS_ST_OUTROS", "ICMS_ENERGIA", "ICMS_PetroCombusLubr", "ICMS_DivAtiva", "ICMS_OUTRAS", "IPVA", "ITCD", "TAXAS", "OUTROS", "TotOutrosTributos", "TotRecTributaria"})
in
    #"Substitui null /ZERO"



Metadados:
Dados referente aos tributos estaduais, informados por cada unidade federada, considerando o disposto no Convênio ICMS 98/96, através do Sistema Gestor dos Dados Econômicos Fiscais – SIGDEF.

Data Início: janeiro/1997
Periodicidade: Mensal
Fonte: https://dados.gov.br/dataset/boletim-de-arrecadacao-dos-tributos-estaduais

Maiores ecxplicações disponíveis em: https://www.confaz.fazenda.gov.br/boletim-de-arrecadacao-dos-tributos-estaduais