f_SELIC


let
    Fonte = Json.Document(Web.Contents("https://api.bcb.gov.br/dados/serie/bcdata.sgs.4189/dados?formato=json&dataInicial=" & Date.ToText(MenorData,"MM/dd/yyyy") & "&dataFinal=" & Text.Replace(DataAtual, "-","/") )),
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"data", "valor"}, {"data", "valor"}),
    #"Valor Substituído" = Table.ReplaceValue(#"Column1 Expandido",".",",",Replacer.ReplaceText,{"valor"}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Valor Substituído",{{"valor", "Taxa_SELIC_Periodo"}, {"data", "data_original"}}),
    #"Data Analisada" = Table.TransformColumns(#"Colunas Renomeadas",{{"data_original", each Date.From(DateTimeZone.From(_)), type date}}),
    #"Cria Col Data dia 15" = Table.AddColumn(#"Data Analisada", "Data", each Date.AddDays([data_original],14)),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cria Col Data dia 15",{{"Data", type date}, {"Taxa_SELIC_Periodo", type number}}),
    #"Filtra por menorData" = Table.SelectRows(#"Tipo Alterado", each [Data] >= Date.AddYears(MenorData,-1))
in
    #"Filtra por menorData"


METADADOS:
Histórico das taxas de juros fixadas pelo Copom e evolução que são registradas diariamente no Sistema Especial de Liquidação e de Custódia (Selic), consiste na taxa média cobrada em negociações com títulos emitidos pelo Tesouro Nacional, uma taxa de juros de referência para os demais juros da economia. Divulgação em % a.a.

unidade: Índice

Fonte: https://www.bcb.gov.br/controleinflacao/historicotaxasjuros