INPC_API_IBGE

let
    VarPerCalendario = Text.Range(Lines.ToText(Mes_Ano[AnoMes], "|"), Text.PositionOf(Lines.ToText(Mes_Ano[AnoMes], "|"),"199912|")+7),
    VarPeriodos = Text.Middle(VarPerCalendario, 0, Text.PositionOf(VarPerCalendario, Text.Combine({"|", AnoMesAtual,"|"}))+7),
    Fonte = Json.Document(Web.Contents("https://servicodados.ibge.gov.br/api/v3/agregados/1737/periodos/"& VarPeriodos & "/variaveis/2266|63|2263|2264|69|2265?localidades=N1[all]")),
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"id", "variavel", "unidade", "resultados"}, {"id", "variavel", "unidade", "resultados"}),
    #"resultados Expandido" = Table.ExpandListColumn(#"Column1 Expandido", "resultados"),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"resultados Expandido",{{"resultados", type any}}),
    #"resultados Expandido1" = Table.ExpandRecordColumn(#"Tipo Alterado", "resultados", {"series"}, {"resultados.series"}),
    #"Substitui IPCA_Indice" = Table.ReplaceValue(#"resultados Expandido1","IPCA - Número-índice (base: dezembro de 1993 = 100)","IPCA_Indice",Replacer.ReplaceText,{"variavel"}),
    #"Substitui IPCA_VarMES" = Table.ReplaceValue(#"Substitui IPCA_Indice","IPCA - Variação mensal","IPCA_VarMES",Replacer.ReplaceText,{"variavel"}),
    #"Substitui IPCA_VarTRIM" = Table.ReplaceValue(#"Substitui IPCA_VarMES","IPCA - Variação acumulada em 3 meses","IPCA_VarTRIM",Replacer.ReplaceText,{"variavel"}),
    #"Substitui IPCA_VarSEM" = Table.ReplaceValue(#"Substitui IPCA_VarTRIM","IPCA - Variação acumulada em 6 meses","IPCA_VarSEM",Replacer.ReplaceText,{"variavel"}),
    #"Substitui IPCA_VarANO" = Table.ReplaceValue(#"Substitui IPCA_VarSEM","IPCA - Variação acumulada no ano","IPCA_VarANO",Replacer.ReplaceText,{"variavel"}),
    #"Substitui IPCA_Var12M" = Table.ReplaceValue(#"Substitui IPCA_VarANO","IPCA - Variação acumulada em 12 meses","IPCA_Var12M",Replacer.ReplaceText,{"variavel"}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Substitui IPCA_Var12M",{"unidade", "id"}),
    #"resultados.series Expandido" = Table.ExpandListColumn(#"Colunas Removidas", "resultados.series"),
    #"resultados.series Expandido1" = Table.ExpandRecordColumn(#"resultados.series Expandido", "resultados.series", {"serie"}, {"serie"}),
    #"serie Expandido2" = Table.ExpandRecordColumn(#"resultados.series Expandido1", "serie", Text.Split(VarPeriodos,"|")),
    #"Outras Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"serie Expandido2", {"variavel"}, "Atributo", "Valor"),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Outras Colunas Não Dinâmicas",{"Atributo", "variavel", "Valor"}),
    #"Valor Substituído6" = Table.ReplaceValue(#"Colunas Reordenadas",".",",",Replacer.ReplaceText,{"Valor"}),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Valor Substituído6",{{"Valor", type number}}),
    #"Coluna em pivô" = Table.Pivot(#"Tipo Alterado1", List.Distinct(#"Tipo Alterado1"[variavel]), "variavel", "Valor", List.Sum),
    #"Linhas Classificadas" = Table.Sort(#"Coluna em pivô",{{"Atributo", Order.Descending}}),
    #"Últimos caracteres inseridos" = Table.AddColumn(#"Linhas Classificadas", "Últimos caracteres", each Text.End([Atributo], 2), type text),
    #"Primeiros caracteres extraídos" = Table.TransformColumns(#"Últimos caracteres inseridos", {{"Atributo", each Text.Start(_, 4), type text}}),
    #"Colunas Mescladas" = Table.CombineColumns(#"Primeiros caracteres extraídos",{"Últimos caracteres", "Atributo"},Combiner.CombineTextByDelimiter("/", QuoteStyle.None),"DATA"),
    #"Prefixo Adicionado" = Table.TransformColumns(#"Colunas Mescladas", {{"DATA", each "15/" & _, type text}}),
    #"Cria Col Caminho" = Table.AddColumn(#"Prefixo Adicionado", "Caminho", each Caminho, type text),
    #"Adição Inserida" = Table.AddColumn(#"Cria Col Caminho", "TaxaIPCA", each [IPCA_VarMES] + 1, type number),
    #"Executar script Python" = Python.Execute("# 'dataset' tem os dados de entrada para este script#(lf)# -*- encoding: utf-8 -*-#(lf)import pandas as pd#(lf)import numpy as np#(lf)import os#(lf)#(lf)from datetime import date#(lf)from datetime import date, timedelta#(lf)from dateutil.relativedelta import relativedelta#(lf)#(lf)#(lf)#(lf)# Converte o valor do IPCA#(lf)dataset['IPCA_VarMES'] = pd.to_numeric(dataset['IPCA_VarMES'],errors = 'coerce')#(lf)#(lf)#(lf)# Fazendo o Cálculo#(lf)produto = []#(lf)apr = 1#(lf)for numr in dataset['IPCA_VarMES']:#(lf)  produto.append(apr)#(lf)  apr = apr/(1 + numr/100)#(lf)  #print(numr, apr) #(lf)  #(lf)#(lf)dataset['IPCA_Ind'] = produto #(lf)#(lf)# Fazendo o Cálculo  #(lf)dataset['IpcaBaseCal'] = (1 + dataset.IPCA_VarMES/100)/dataset.IPCA_Ind#(lf)#(lf)# Coloca para o mês seguinte#(lf)dataset['IpcaBase'] = dataset.IpcaBaseCal.shift(1)#(lf)#(lf)# Iguala a data base como 1#(lf)dataset['IpcaBase'] = dataset['IpcaBase'].replace(np.nan, 1)#(lf)#(lf)# exclui a coluna de cálculo#(lf)dataset = dataset.drop(columns=['IpcaBaseCal'])#(lf)#(lf)# Converte o valor do IPCA #(lf)dataset['IpcaBase'] = pd.to_numeric(dataset['IpcaBase'],errors = 'coerce')#(lf)#(lf)# Pega o Caminho já definido#(lf)Caminho = dataset['Caminho'][0]#(lf)#(lf)# Seleciona o caminho do Arquivo#(lf)basedir = Caminho + ""/ArquivosParaUnificar/""#(lf)#(lf)# Nome do arquivo#(lf)nomearq = ""IPCA_API_IBGE.csv""#(lf)#(lf)# cria um diretório para armazenar o arquivo comparâmetro para não criar se já existir#(lf)os.makedirs(os.path.abspath(os.path.dirname(basedir)), exist_ok=True)#(lf)#(lf)basedir = os.path.abspath(os.path.dirname(basedir))#(lf)#(lf)# Apaga o arquivo se foi criado#(lf)if os.path.isfile(os.path.join(basedir, nomearq)):#(lf)  # Se existe apaga o arquivo#(lf)  os.remove(os.path.join(basedir, nomearq))#(lf)#(lf)# Salva o arquivo na Pasta de unificação#(lf)dataset[['DATA', 'TaxaIPCA', 'IPCA_Indice', 'IPCA_VarMES', 'IpcaBase', 'IPCA_VarTRIM', 'IPCA_VarSEM', 'IPCA_VarANO', 'IPCA_Var12M']].to_csv(os.path.join(basedir, nomearq), index = False, sep =';')#(lf)#(lf)dataset = dataset[['DATA', 'TaxaIPCA', 'IPCA_Indice', 'IPCA_VarMES', 'IpcaBase', 'IPCA_VarTRIM', 'IPCA_VarSEM', 'IPCA_VarANO', 'IPCA_Var12M']]#(lf)print(dataset)#(lf)",[dataset=#"Adição Inserida"]),
    #"Outras Colunas Removidas" = Table.SelectColumns(#"Executar script Python",{"Value"}),
    #"Value Expandido" = Table.ExpandTableColumn(#"Outras Colunas Removidas", "Value", {"DATA", "TaxaIPCA", "IPCA_Indice", "IPCA_VarMES", "IpcaBase", "IPCA_VarTRIM", "IPCA_VarSEM", "IPCA_VarANO", "IPCA_Var12M"}, {"DATA", "TaxaIPCA", "IPCA_Indice", "IPCA_VarMES", "IpcaBase", "IPCA_VarTRIM", "IPCA_VarSEM", "IPCA_VarANO", "IPCA_Var12M"}),
    #"Data Analisada" = Table.TransformColumns(#"Value Expandido",{{"DATA", each Date.From(DateTimeZone.From(_)), type date}}),
    #"Valor Substituído" = Table.ReplaceValue(#"Data Analisada",".",",",Replacer.ReplaceText,{"TaxaIPCA", "IPCA_Indice", "IPCA_VarMES", "IpcaBase", "IPCA_VarTRIM", "IPCA_VarSEM", "IPCA_VarANO", "IPCA_Var12M"}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Valor Substituído",{{"TaxaIPCA", type number}, {"IPCA_Indice", type number}, {"IPCA_VarMES", type number}, {"IPCA_VarTRIM", type number}, {"IPCA_VarSEM", type number}, {"IPCA_VarANO", type number}, {"IPCA_Var12M", type number}, {"IpcaBase", type number}})
in
    #"Tipo Alterado2"


METADADOS:
Tabela do IBGE do Índice Nacional de Preços ao Consumidor nº 1736- INPC - Série histórica com número-índice (2289), variação mensal (44) e variações acumuladas no ano (68) e em 12 meses (2292). 

Unidade: US$ (milhões)
Periodiciadade: Mensal
Data Início: abr-1979

Fonte:https://servicodados.ibge.gov.br/api/docs/agregados?versao=3#api-bq