IPCA_API_IBGE


let
    Arquivo = "\ArquivosParaUnificar\IPCA_API_IBGE.csv",
    Fonte = Csv.Document(File.Contents(Caminho & Arquivo),[Delimiter=";", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
    #"Valor Substituído" = Table.ReplaceValue(#"Cabeçalhos Promovidos",".",",",Replacer.ReplaceText,{"TaxaIPCA", "IPCA_Indice", "IPCA_VarMES", "IPCA_VarTRIM", "IPCA_VarSEM", "IPCA_VarANO", "IPCA_Var12M"}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Valor Substituído",{{"DATA", type date}, {"TaxaIPCA", type number}, {"IPCA_Indice", type number}, {"IPCA_VarMES", type number}, {"IPCA_VarTRIM", type number}, {"IPCA_VarSEM", type number}, {"IPCA_VarANO", type number}, {"IPCA_Var12M", type number}})
in
    #"Tipo Alterado"


Metadados:
Agrupa o Índice Nacional de Preços ao Consumidor Amplo (IPCA) da Tabela 1737- IPCA - Série histórica com número-índice (2266), variação mensal(63) e variações acumuladas em 3 meses (2263), em 6 meses (2264), no ano (69) e em 12 meses (2265) do IBGE.

Data início: dezembro/1979
Periodicidade: Mensal

Fonte: https://servicodados.ibge.gov.br/api/docs/agregados?versao=3#api-bq